;;; test-self-encoding.el --- Test that produces real output

(add-to-list 'load-path "/data/data/com.termux/files/home/github/meta-log")
(require 'meta-log)
(require 'meta-log-metacircular)
(meta-log-initialize)

;; Test 1: Generate a file containing the system's self-encoding
(princ "Creating self-encoding.json...\n")
(let ((encoding (meta-log-encode-self)))
  (with-temp-file "examples/self-encoding.json"
    (insert (json-encode encoding)))
  (princ "✓ Created examples/self-encoding.json\n\n"))

;; Test 2: Generate a function and save it to a file
(princ "Generating new function...\n")
(meta-log-modify-self
 'test-component
 'self-generated-hello
 '((name)
   (format "Hello %s! I was generated by meta-log at %s"
           name
           (format-time-string "%Y-%m-%d %H:%M:%S"))))

;; Save the generated function to a file
(with-temp-file "examples/generated-function.el"
  (insert ";;; generated-function.el --- Self-generated code\n\n")
  (insert (format ";; Generated at: %s\n\n" (format-time-string "%Y-%m-%d %H:%M:%S")))
  (insert "(defun self-generated-hello (name)\n")
  (insert "  \"A function that was created by meta-log itself!\"\n")
  (insert "  (format \"Hello %s! I was generated by meta-log at %s\"\n")
  (insert "          name\n")
  (insert "          (format-time-string \"%Y-%m-%d %H:%M:%S\")))\n\n")
  (insert ";; Test it:\n")
  (insert (format ";; (self-generated-hello \"World\") => %S\n"
                  (self-generated-hello "World"))))

(princ "✓ Created examples/generated-function.el\n")
(princ (format "✓ Function works: %s\n\n" (self-generated-hello "Test")))

;; Test 3: Bootstrap and save the initialization code
(princ "Bootstrapping system from description...\n")
(let ((spec (meta-log-bootstrap-self "template discovery system")))
  (with-temp-file "examples/bootstrapped-init.el"
    (insert ";;; bootstrapped-init.el --- Self-generated initialization\n\n")
    (insert (format ";; Bootstrapped from: %S\n" (plist-get spec :description)))
    (insert (format ";; Generated at: %s\n\n" (plist-get spec :generated-at)))
    (insert (plist-get spec :init-code)))
  (princ "✓ Created examples/bootstrapped-init.el\n\n"))

;; Test 4: Create a self-description document
(princ "Generating self-description document...\n")
(with-temp-file "examples/system-description.txt"
  (insert "META-LOG SYSTEM SELF-DESCRIPTION\n")
  (insert "=================================\n\n")
  (insert (meta-log-self-describe))
  (insert "\n\n")
  (insert "FULL ENCODING:\n")
  (insert "==============\n\n")
  (insert (format "%S" (meta-log-encode-self))))

(princ "✓ Created examples/system-description.txt\n\n")

(princ "===========================================\n")
(princ "DONE! Created 4 files:\n")
(princ "===========================================\n\n")
(princ "1. examples/self-encoding.json - System structure in JSON\n")
(princ "2. examples/generated-function.el - Self-generated Elisp function\n")
(princ "3. examples/bootstrapped-init.el - Self-bootstrapped initialization\n")
(princ "4. examples/system-description.txt - Natural language self-description\n\n")

(princ "View them:\n")
(princ "  cat examples/self-encoding.json\n")
(princ "  cat examples/generated-function.el\n")
(princ "  cat examples/bootstrapped-init.el\n")
(princ "  cat examples/system-description.txt\n\n")

(provide 'test-self-encoding)
