;;; simple-self-demo.el --- Simple self-encoding demonstration

;;; Commentary:
;; This is a simplified demo that clearly shows self-encoding working.

;;; Code:

(add-to-list 'load-path "/data/data/com.termux/files/home/github/meta-log")
(require 'meta-log)
(require 'meta-log-metacircular)

(princ "\n========================================\n")
(princ "SIMPLE SELF-ENCODING DEMO\n")
(princ "========================================\n\n")

;; Initialize
(princ "Initializing meta-log...\n")
(meta-log-initialize)
(princ "✓ Initialized\n\n")

;; Test 1: Self-Encoding
(princ "TEST 1: Can the system encode itself?\n")
(princ "Running: (meta-log-encode-self)\n\n")

(let ((encoding (meta-log-encode-self)))
  (princ (format "Result:\n"))
  (princ (format "  System Name: %s\n" (plist-get encoding :name)))
  (princ (format "  Version: %s\n" (plist-get encoding :version)))
  (princ (format "  Dimension: %s\n" (plist-get encoding :dimension)))
  (princ (format "  Can modify self: %s\n" (plist-get encoding :can-modify-self)))
  (princ (format "  Number of components: %d\n\n"
                 (length (plist-get encoding :components))))

  (princ "Components:\n")
  (dolist (comp (plist-get encoding :components))
    (princ (format "  • %s (%s)\n"
                   (plist-get comp :name)
                   (plist-get comp :dimension)))))

(princ "\n✓ System successfully encoded itself!\n\n")

;; Test 2: Self-Description
(princ "========================================\n")
(princ "TEST 2: Can the system describe itself?\n")
(princ "Running: (meta-log-self-describe)\n\n")

(let ((description (meta-log-self-describe)))
  (princ (format "Result:\n%s\n" description)))

(princ "\n✓ System described itself in natural language!\n\n")

;; Test 3: Self-Query
(princ "========================================\n")
(princ "TEST 3: Can the system answer questions about itself?\n\n")

(let ((question "What components does meta-log have?"))
  (princ (format "Question: %s\n" question))
  (princ (format "Answer:\n%s\n\n" (meta-log-query-self question))))

(let ((question "Can it modify itself?"))
  (princ (format "Question: %s\n" question))
  (princ (format "Answer: %s\n\n" (meta-log-query-self question))))

(princ "✓ System answered questions about itself!\n\n")

;; Test 4: Self-Modification
(princ "========================================\n")
(princ "TEST 4: Can the system modify its own code?\n\n")

(princ "Creating a new function called 'demo-generated-function'...\n")

(meta-log-modify-self
 'meta-log-metacircular
 'demo-generated-function
 '(()
   (format "I am a function that was generated by the system itself at %s!"
           (format-time-string "%Y-%m-%d %H:%M:%S"))))

(princ "\nTesting the newly created function...\n")
(princ (format "Result: %s\n" (demo-generated-function)))

(princ "\n✓ System modified itself and created a working function!\n\n")

;; Test 5: Bootstrap
(princ "========================================\n")
(princ "TEST 5: Can the system bootstrap from a description?\n\n")

(let ((spec (meta-log-bootstrap-self "logic system with templates and federation")))
  (princ (format "\nBootstrapped system has %d components\n"
                 (length (plist-get spec :components))))
  (princ "\nGenerated initialization code:\n")
  (princ (plist-get spec :init-code)))

(princ "\n\n✓ System bootstrapped itself from description!\n\n")

;; Summary
(princ "========================================\n")
(princ "SUMMARY: ALL TESTS PASSED!\n")
(princ "========================================\n\n")

(princ "The system demonstrated:\n")
(princ "  ✓ Self-Encoding    - Represented its own structure\n")
(princ "  ✓ Self-Description - Described itself in natural language\n")
(princ "  ✓ Self-Query       - Answered questions about itself\n")
(princ "  ✓ Self-Modification - Created new code at runtime\n")
(princ "  ✓ Self-Bootstrap   - Generated itself from description\n\n")

(princ "This is a METACIRCULAR system!\n\n")

(provide 'simple-self-demo)
;;; simple-self-demo.el ends here
